#!/bin/bash

build() {
    local mod

    add_module dm-crypt
    add_module dm-integrity
    if [[ $CRYPTO_MODULES ]]; then
        for mod in $CRYPTO_MODULES; do
            add_module "$mod"
        done
    else
        add_all_modules /crypto/
    fi

    add_binary fido2luks
    add_binary dmsetup
    add_file /usr/lib/udev/rules.d/10-dm.rules
    add_file /usr/lib/udev/rules.d/13-dm-disk.rules
    add_file /usr/lib/udev/rules.d/95-dm-notify.rules
    add_file /usr/lib/initcpio/udev/11-dm-initramfs.rules /usr/lib/udev/rules.d/11-dm-initramfs.rules
    add_file /etc/fido2luks.conf /etc/fido2luks.conf

    add_runscript
}

help() {
    cat <<HELPEOF
This hook allows to decrypt LUKS2 partition using FIDO2 compatible authenticator
HELPEOF
}
